// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for IOS}.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform}.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKUimx-86ytzwIKKDS7d1ruACuHXmF-Mg',
    appId: '1:486108475634:android:fb8d533770b5ce03c1e06b',
    messagingSenderId: '486108475634',
    projectId: 'cme-assessment',
  );
}
